# Generated by Django 5.1 on 2024-12-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('offered_by', models.CharField(max_length=100)),
                ('offered_to', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('schedule', models.CharField(max_length=100)),
            ],
        ),
    ]
